#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"

BOARD_SIZE="${BOARD_SIZE:-15}"
WIN_LENGTH="${WIN_LENGTH:-5}"
DEVICE="${DEVICE:-auto}"
SEED="${SEED:-42}"

DATASET_PATH="${DATASET_PATH:-$ROOT_DIR/heuristic_dataset_15x15_5.npz}"
PRETRAIN_CHECKPOINT="${PRETRAIN_CHECKPOINT:-$ROOT_DIR/gomoku_bootstrap_15x15_5_pretrain.pt}"
FINETUNE_CHECKPOINT="${FINETUNE_CHECKPOINT:-$ROOT_DIR/gomoku_bootstrap_15x15_5.pt}"

CHANNELS="${CHANNELS:-128}"
CONV_LAYERS="${CONV_LAYERS:-8}"

GENERATE_GAMES="${GENERATE_GAMES:-12000}"
GENERATE_RANDOM_OPENING_MOVES="${GENERATE_RANDOM_OPENING_MOVES:-2}"
GENERATE_POLICY_SMOOTHING="${GENERATE_POLICY_SMOOTHING:-0.05}"
GENERATE_LOG_EVERY_GAMES="${GENERATE_LOG_EVERY_GAMES:-200}"

PRETRAIN_STEPS="${PRETRAIN_STEPS:-12000}"
PRETRAIN_BATCH_SIZE="${PRETRAIN_BATCH_SIZE:-256}"
PRETRAIN_LR="${PRETRAIN_LR:-3e-4}"
PRETRAIN_WEIGHT_DECAY="${PRETRAIN_WEIGHT_DECAY:-1e-4}"
PRETRAIN_VALUE_COEF="${PRETRAIN_VALUE_COEF:-1.0}"
PRETRAIN_EVAL_EVERY="${PRETRAIN_EVAL_EVERY:-500}"
PRETRAIN_EVAL_GAMES="${PRETRAIN_EVAL_GAMES:-20}"
PRETRAIN_EVAL_HEURISTIC_GAMES="${PRETRAIN_EVAL_HEURISTIC_GAMES:-8}"
PRETRAIN_EVAL_AGENT="${PRETRAIN_EVAL_AGENT:-policy}"
PRETRAIN_EVAL_MCTS_SIMS="${PRETRAIN_EVAL_MCTS_SIMS:-128}"
PRETRAIN_C_PUCT="${PRETRAIN_C_PUCT:-1.5}"
PRETRAIN_SAVE_EVERY="${PRETRAIN_SAVE_EVERY:-1000}"
PRETRAIN_LOG_EVERY_STEPS="${PRETRAIN_LOG_EVERY_STEPS:-100}"

FINETUNE_ITERATIONS="${FINETUNE_ITERATIONS:-1500}"
FINETUNE_GAMES_PER_ITER="${FINETUNE_GAMES_PER_ITER:-32}"
FINETUNE_TRAIN_STEPS="${FINETUNE_TRAIN_STEPS:-64}"
FINETUNE_BATCH_SIZE="${FINETUNE_BATCH_SIZE:-128}"
FINETUNE_BUFFER_SIZE="${FINETUNE_BUFFER_SIZE:-100000}"
FINETUNE_LR="${FINETUNE_LR:-3e-4}"
FINETUNE_WEIGHT_DECAY="${FINETUNE_WEIGHT_DECAY:-1e-4}"
FINETUNE_VALUE_COEF="${FINETUNE_VALUE_COEF:-1.0}"
FINETUNE_MCTS_SIMS="${FINETUNE_MCTS_SIMS:-256}"
FINETUNE_EVAL_MCTS_SIMS="${FINETUNE_EVAL_MCTS_SIMS:-512}"
FINETUNE_C_PUCT="${FINETUNE_C_PUCT:-1.5}"
FINETUNE_TEMPERATURE="${FINETUNE_TEMPERATURE:-0.6}"
FINETUNE_TEMPERATURE_DROP_MOVES="${FINETUNE_TEMPERATURE_DROP_MOVES:-3}"
FINETUNE_DIRICHLET_ALPHA="${FINETUNE_DIRICHLET_ALPHA:-0.03}"
FINETUNE_NOISE_EPS="${FINETUNE_NOISE_EPS:-0.10}"
FINETUNE_RANDOM_OPENING_MOVES="${FINETUNE_RANDOM_OPENING_MOVES:-2}"
FINETUNE_EVAL_EVERY="${FINETUNE_EVAL_EVERY:-10}"
FINETUNE_EVAL_GAMES="${FINETUNE_EVAL_GAMES:-20}"
FINETUNE_EVAL_HEURISTIC_GAMES="${FINETUNE_EVAL_HEURISTIC_GAMES:-8}"
FINETUNE_EVAL_TRACE_GAMES="${FINETUNE_EVAL_TRACE_GAMES:-1}"
FINETUNE_EVAL_TRACE_MAX_MOVES="${FINETUNE_EVAL_TRACE_MAX_MOVES:-20}"
FINETUNE_SAVE_EVERY="${FINETUNE_SAVE_EVERY:-10}"
FINETUNE_LOG_EVERY_GAMES="${FINETUNE_LOG_EVERY_GAMES:-4}"
FINETUNE_LOG_EVERY_TRAIN_STEPS="${FINETUNE_LOG_EVERY_TRAIN_STEPS:-16}"

echo
echo "=== Stage 1: generate heuristic dataset ==="
python "$ROOT_DIR/gomoku_bootstrap.py" generate \
  --board-size "$BOARD_SIZE" \
  --win-length "$WIN_LENGTH" \
  --games "$GENERATE_GAMES" \
  --random-opening-moves "$GENERATE_RANDOM_OPENING_MOVES" \
  --policy-smoothing "$GENERATE_POLICY_SMOOTHING" \
  --log-every-games "$GENERATE_LOG_EVERY_GAMES" \
  --seed "$SEED" \
  --output "$DATASET_PATH"

echo
echo "=== Stage 2: heuristic pretrain ==="
python "$ROOT_DIR/gomoku_bootstrap.py" pretrain \
  --dataset "$DATASET_PATH" \
  --channels "$CHANNELS" \
  --conv-layers "$CONV_LAYERS" \
  --steps "$PRETRAIN_STEPS" \
  --batch-size "$PRETRAIN_BATCH_SIZE" \
  --lr "$PRETRAIN_LR" \
  --weight-decay "$PRETRAIN_WEIGHT_DECAY" \
  --value-coef "$PRETRAIN_VALUE_COEF" \
  --eval-every "$PRETRAIN_EVAL_EVERY" \
  --eval-games "$PRETRAIN_EVAL_GAMES" \
  --eval-heuristic-games "$PRETRAIN_EVAL_HEURISTIC_GAMES" \
  --eval-agent "$PRETRAIN_EVAL_AGENT" \
  --eval-mcts-sims "$PRETRAIN_EVAL_MCTS_SIMS" \
  --c-puct "$PRETRAIN_C_PUCT" \
  --save-every "$PRETRAIN_SAVE_EVERY" \
  --log-every-steps "$PRETRAIN_LOG_EVERY_STEPS" \
  --seed "$SEED" \
  --device "$DEVICE" \
  --checkpoint "$PRETRAIN_CHECKPOINT"

echo
echo "=== Stage 3: MCTS finetune ==="
python "$ROOT_DIR/gomoku_bootstrap.py" finetune \
  --board-size "$BOARD_SIZE" \
  --win-length "$WIN_LENGTH" \
  --channels "$CHANNELS" \
  --conv-layers "$CONV_LAYERS" \
  --iterations "$FINETUNE_ITERATIONS" \
  --games-per-iter "$FINETUNE_GAMES_PER_ITER" \
  --train-steps "$FINETUNE_TRAIN_STEPS" \
  --batch-size "$FINETUNE_BATCH_SIZE" \
  --buffer-size "$FINETUNE_BUFFER_SIZE" \
  --lr "$FINETUNE_LR" \
  --weight-decay "$FINETUNE_WEIGHT_DECAY" \
  --value-coef "$FINETUNE_VALUE_COEF" \
  --mcts-sims "$FINETUNE_MCTS_SIMS" \
  --eval-mcts-sims "$FINETUNE_EVAL_MCTS_SIMS" \
  --c-puct "$FINETUNE_C_PUCT" \
  --temperature "$FINETUNE_TEMPERATURE" \
  --temperature-drop-moves "$FINETUNE_TEMPERATURE_DROP_MOVES" \
  --dirichlet-alpha "$FINETUNE_DIRICHLET_ALPHA" \
  --noise-eps "$FINETUNE_NOISE_EPS" \
  --random-opening-moves "$FINETUNE_RANDOM_OPENING_MOVES" \
  --eval-every "$FINETUNE_EVAL_EVERY" \
  --eval-games "$FINETUNE_EVAL_GAMES" \
  --eval-heuristic-games "$FINETUNE_EVAL_HEURISTIC_GAMES" \
  --eval-trace-games "$FINETUNE_EVAL_TRACE_GAMES" \
  --eval-trace-max-moves "$FINETUNE_EVAL_TRACE_MAX_MOVES" \
  --save-every "$FINETUNE_SAVE_EVERY" \
  --log-every-games "$FINETUNE_LOG_EVERY_GAMES" \
  --log-every-train-steps "$FINETUNE_LOG_EVERY_TRAIN_STEPS" \
  --seed "$SEED" \
  --device "$DEVICE" \
  --init-checkpoint "$PRETRAIN_CHECKPOINT" \
  --checkpoint "$FINETUNE_CHECKPOINT"
