#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
PYTHON_BIN="${PYTHON_BIN:-python}"

CHANNELS="${CHANNELS:-128}"
CONV_LAYERS="${CONV_LAYERS:-8}"
ITERATIONS="${ITERATIONS:-1200}"
GAMES_PER_ITER="${GAMES_PER_ITER:-48}"
TRAIN_STEPS="${TRAIN_STEPS:-64}"
BATCH_SIZE="${BATCH_SIZE:-128}"
BUFFER_SIZE="${BUFFER_SIZE:-40000}"
LR="${LR:-3e-4}"
WEIGHT_DECAY="${WEIGHT_DECAY:-1e-4}"
VALUE_COEF="${VALUE_COEF:-1.0}"
MCTS_SIMS="${MCTS_SIMS:-96}"
EVAL_MCTS_SIMS="${EVAL_MCTS_SIMS:-192}"
C_PUCT="${C_PUCT:-1.5}"
TEMPERATURE="${TEMPERATURE:-0.8}"
TEMPERATURE_DROP_MOVES="${TEMPERATURE_DROP_MOVES:-6}"
DIRICHLET_ALPHA="${DIRICHLET_ALPHA:-0.30}"
NOISE_EPS="${NOISE_EPS:-0.12}"
RANDOM_OPENING_MOVES="${RANDOM_OPENING_MOVES:-0}"
EVAL_EVERY="${EVAL_EVERY:-5}"
EVAL_GAMES="${EVAL_GAMES:-20}"
EVAL_HEURISTIC_GAMES="${EVAL_HEURISTIC_GAMES:-8}"
EVAL_TRACE_GAMES="${EVAL_TRACE_GAMES:-1}"
EVAL_HEURISTIC_TRACE_GAMES="${EVAL_HEURISTIC_TRACE_GAMES:-1}"
EVAL_TRACE_MAX_MOVES="${EVAL_TRACE_MAX_MOVES:-20}"
SAVE_EVERY="${SAVE_EVERY:-10}"
LOG_EVERY_GAMES="${LOG_EVERY_GAMES:-12}"
LOG_EVERY_TRAIN_STEPS="${LOG_EVERY_TRAIN_STEPS:-16}"
EARLY_STOP_LOSS="${EARLY_STOP_LOSS:-0.35}"
EARLY_STOP_PATIENCE="${EARLY_STOP_PATIENCE:-15}"
EARLY_STOP_MIN_ITERATIONS="${EARLY_STOP_MIN_ITERATIONS:-100}"
EARLY_STOP_HEURISTIC_WIN_RATE="${EARLY_STOP_HEURISTIC_WIN_RATE:-0.70}"
EARLY_STOP_HEURISTIC_PATIENCE="${EARLY_STOP_HEURISTIC_PATIENCE:-3}"
SELFPLAY_WORKERS="${SELFPLAY_WORKERS:-1}"
SELFPLAY_WORKER_DEVICE="${SELFPLAY_WORKER_DEVICE:-cpu}"
SEED="${SEED:-42}"
DEVICE="${DEVICE:-auto}"

OUTPUT_CHECKPOINT="${OUTPUT_CHECKPOINT:-$ROOT_DIR/gomoku_az_5x5_4.pt}"

CMD=(
  "$PYTHON_BIN" "$ROOT_DIR/gomoku_alphazero.py" train
  --board-size 5
  --win-length 4
  --channels "$CHANNELS"
  --conv-layers "$CONV_LAYERS"
  --iterations "$ITERATIONS"
  --games-per-iter "$GAMES_PER_ITER"
  --train-steps "$TRAIN_STEPS"
  --batch-size "$BATCH_SIZE"
  --buffer-size "$BUFFER_SIZE"
  --lr "$LR"
  --weight-decay "$WEIGHT_DECAY"
  --value-coef "$VALUE_COEF"
  --mcts-sims "$MCTS_SIMS"
  --eval-mcts-sims "$EVAL_MCTS_SIMS"
  --c-puct "$C_PUCT"
  --temperature "$TEMPERATURE"
  --temperature-drop-moves "$TEMPERATURE_DROP_MOVES"
  --dirichlet-alpha "$DIRICHLET_ALPHA"
  --noise-eps "$NOISE_EPS"
  --random-opening-moves "$RANDOM_OPENING_MOVES"
  --eval-every "$EVAL_EVERY"
  --eval-games "$EVAL_GAMES"
  --eval-heuristic-games "$EVAL_HEURISTIC_GAMES"
  --eval-trace-games "$EVAL_TRACE_GAMES"
  --eval-heuristic-trace-games "$EVAL_HEURISTIC_TRACE_GAMES"
  --eval-trace-max-moves "$EVAL_TRACE_MAX_MOVES"
  --save-every "$SAVE_EVERY"
  --log-every-games "$LOG_EVERY_GAMES"
  --log-every-train-steps "$LOG_EVERY_TRAIN_STEPS"
  --early-stop-loss "$EARLY_STOP_LOSS"
  --early-stop-patience "$EARLY_STOP_PATIENCE"
  --early-stop-min-iterations "$EARLY_STOP_MIN_ITERATIONS"
  --early-stop-heuristic-win-rate "$EARLY_STOP_HEURISTIC_WIN_RATE"
  --early-stop-heuristic-patience "$EARLY_STOP_HEURISTIC_PATIENCE"
  --selfplay-workers "$SELFPLAY_WORKERS"
  --selfplay-worker-device "$SELFPLAY_WORKER_DEVICE"
  --seed "$SEED"
  --device "$DEVICE"
  --checkpoint "$OUTPUT_CHECKPOINT"
)

if [[ -n "${INIT_CHECKPOINT:-}" ]]; then
  CMD+=(--init-checkpoint "$INIT_CHECKPOINT")
fi

printf 'Running command:\n%s\n' "${CMD[*]}"
exec "${CMD[@]}"
