#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
PYTHON_BIN="${PYTHON_BIN:-python}"

BOARD_SIZE="${BOARD_SIZE:-15}"
WIN_LENGTH="${WIN_LENGTH:-5}"
CHANNELS="${CHANNELS:-320}"
CONV_LAYERS="${CONV_LAYERS:-12}"
ITERATIONS="${ITERATIONS:-3000}"
GAMES_PER_ITER="${GAMES_PER_ITER:-64}"
PPO_EPOCHS="${PPO_EPOCHS:-8}"
MINIBATCH_SIZE="${MINIBATCH_SIZE:-256}"
LR="${LR:-3e-4}"
WEIGHT_DECAY="${WEIGHT_DECAY:-1e-4}"
GAMMA="${GAMMA:-0.99}"
CLIP_EPS="${CLIP_EPS:-0.2}"
ENTROPY_COEF="${ENTROPY_COEF:-0.01}"
VALUE_COEF="${VALUE_COEF:-1.0}"
MAX_GRAD_NORM="${MAX_GRAD_NORM:-1.0}"
RANDOM_OPENING_MOVES="${RANDOM_OPENING_MOVES:-2}"
EVAL_EVERY="${EVAL_EVERY:-10}"
EVAL_GAMES="${EVAL_GAMES:-20}"
EVAL_HEURISTIC_GAMES="${EVAL_HEURISTIC_GAMES:-8}"
EVAL_TRACE_GAMES="${EVAL_TRACE_GAMES:-1}"
EVAL_TRACE_MAX_MOVES="${EVAL_TRACE_MAX_MOVES:-20}"
LOG_EVERY_GAMES="${LOG_EVERY_GAMES:-8}"
SAVE_EVERY="${SAVE_EVERY:-10}"
SEED="${SEED:-42}"
DEVICE="${DEVICE:-auto}"

REWARD_WIN="${REWARD_WIN:-8.0}"
REWARD_DRAW="${REWARD_DRAW:-0.0}"
REWARD_BLOCK_WIN="${REWARD_BLOCK_WIN:-2.0}"
REWARD_OPEN_FOUR="${REWARD_OPEN_FOUR:-1.5}"
REWARD_CLOSED_FOUR="${REWARD_CLOSED_FOUR:-0.8}"
REWARD_OPEN_THREE="${REWARD_OPEN_THREE:-0.55}"
REWARD_CLOSED_THREE="${REWARD_CLOSED_THREE:-0.2}"
REWARD_OPEN_TWO="${REWARD_OPEN_TWO:-0.05}"
REWARD_DOUBLE_THREAT="${REWARD_DOUBLE_THREAT:-2.5}"
REWARD_ALLOW_OPP_WIN="${REWARD_ALLOW_OPP_WIN:-3.0}"
REWARD_CENTER_BIAS="${REWARD_CENTER_BIAS:-0.01}"
MAX_ABS_STEP_REWARD="${MAX_ABS_STEP_REWARD:-10.0}"
RETURN_CLIP="${RETURN_CLIP:-10.0}"

OUTPUT_CHECKPOINT="${OUTPUT_CHECKPOINT:-$ROOT_DIR/gomoku_reward_15x15_5.pt}"

CMD=(
  "$PYTHON_BIN" "$ROOT_DIR/gomoku_reward_ppo.py" train
  --board-size "$BOARD_SIZE"
  --win-length "$WIN_LENGTH"
  --channels "$CHANNELS"
  --conv-layers "$CONV_LAYERS"
  --iterations "$ITERATIONS"
  --games-per-iter "$GAMES_PER_ITER"
  --ppo-epochs "$PPO_EPOCHS"
  --minibatch-size "$MINIBATCH_SIZE"
  --lr "$LR"
  --weight-decay "$WEIGHT_DECAY"
  --gamma "$GAMMA"
  --clip-eps "$CLIP_EPS"
  --entropy-coef "$ENTROPY_COEF"
  --value-coef "$VALUE_COEF"
  --max-grad-norm "$MAX_GRAD_NORM"
  --random-opening-moves "$RANDOM_OPENING_MOVES"
  --eval-every "$EVAL_EVERY"
  --eval-games "$EVAL_GAMES"
  --eval-heuristic-games "$EVAL_HEURISTIC_GAMES"
  --eval-trace-games "$EVAL_TRACE_GAMES"
  --eval-trace-max-moves "$EVAL_TRACE_MAX_MOVES"
  --log-every-games "$LOG_EVERY_GAMES"
  --save-every "$SAVE_EVERY"
  --seed "$SEED"
  --device "$DEVICE"
  --checkpoint "$OUTPUT_CHECKPOINT"
  --reward-win "$REWARD_WIN"
  --reward-draw "$REWARD_DRAW"
  --reward-block-win "$REWARD_BLOCK_WIN"
  --reward-open-four "$REWARD_OPEN_FOUR"
  --reward-closed-four "$REWARD_CLOSED_FOUR"
  --reward-open-three "$REWARD_OPEN_THREE"
  --reward-closed-three "$REWARD_CLOSED_THREE"
  --reward-open-two "$REWARD_OPEN_TWO"
  --reward-double-threat "$REWARD_DOUBLE_THREAT"
  --reward-allow-opp-win "$REWARD_ALLOW_OPP_WIN"
  --reward-center-bias "$REWARD_CENTER_BIAS"
  --max-abs-step-reward "$MAX_ABS_STEP_REWARD"
  --return-clip "$RETURN_CLIP"
)

if [[ -n "${INIT_CHECKPOINT:-}" ]]; then
  CMD+=(--init-checkpoint "$INIT_CHECKPOINT")
fi
if [[ "${SYMMETRY_AUGMENT:-1}" == "0" ]]; then
  CMD+=(--no-symmetry-augment)
fi

printf 'Running command:\n%s\n' "${CMD[*]}"
exec "${CMD[@]}"
